### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by LZHLilE** [Gabesarch/TIDEE#2]
@Gabesarch Hi, sorry to bother you. I have set the "--do_headless_rendering" to True, but it still remaids me of the requirement of X11 sever.
![image](https://github.com/Gabesarch/TIDEE/assets/106733353/779fe9be-7ace-40ae-8993-bcb3259e0fff)
![image](https://github.com/Gabesarch/TIDEE/assets/106733353/ba8f43a9-949c-44b5-9b36-50fff3741222)

**Comment by LZHLilE** [comment]
I am running TIDEE on the RoomR benchmark.

**Comment by Gabesarch** [comment]
Hi, 

Headless support was only available for the tidy task. I have pushed support for headless rendering on the rearrangement task in the most recent commit: https://github.com/Gabesarch/TIDEE/commit/854edcf1cfb6f9e62113d2df80fc7ff8fa85a566.

**Comment by LZHLilE** [comment]
@Gabesarch Thanks a lot, it works for me well! However, I have also tried using the X server to render the Unity window on my local PC encountering an issue: 
![image](https://github.com/Gabesarch/TIDEE/assets/106733353/dbd7b65e-fd91-4fd8-8adb-2a0e623355a5)
There is a window poping out which closed suddenly a few seconds later. It seems like a X server problem and I cannot find any a solution these days. This is wired because I can succeaafully run a demo code of AI2-THOR platform and the poped window wont shut down:
`from ai2thor.controller import Controller`
`controller = Controller(scene="FloorPlan10")`
`event = controller.step(action="RotateRight")`
`metadata = event.metadata`
`print(event, event.metadata.keys())`
This is of vatil importance to my study. I'd appreciate it if you could help me again.

**Comment by Gabesarch** [comment]
It's hard to narrow down the exact cause of the issue without knowing your setup and details of the error.

Here are some things you could try:
- You might try setting the `x_display` parameter to `None` here: https://github.com/Gabesarch/TIDEE/blob/rearrange2023/models/aithor_rearrange.py#L146C1-L146C1
- Check what port your x display is open on (using a command like `nvidia-smi`) and specify that port via `--server_port`. 

If these do not help, and you have more information on your setup and the error you are seeing, please send those.
